/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    id("com.github.johnrengelman.shadow") version "8.1.1"
    id("org.panteleyev.jpackageplugin") version "1.6.0"
}

repositories {
    mavenCentral()
}

dependencies {
    api(libs.org.slf4j.slf4j.api)
    api(libs.org.apache.logging.log4j.log4j.slf4j2.impl)
    api(libs.org.apache.logging.log4j.log4j.core)
    api(libs.com.google.code.gson.gson)
    api(libs.commons.cli.commons.cli)
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.2")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    testImplementation(libs.org.mockito.mockito.core)
    testImplementation(libs.org.mockito.mockito.junit.jupiter)
}

group = "oripa"
version = "1.73"
description = "oripa"
java.sourceCompatibility = JavaVersion.VERSION_21

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

// run: gradle shadowJar
// fat jar will be created in build/libs as oripa-x.yz-all.jar
tasks.withType<Jar> {
    manifest {
        attributes["Main-Class"] = "oripa.ORIPA"
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
    options.compilerArgs.add("-Xlint:unchecked")
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

tasks.test {
    useJUnitPlatform()
}

task("copyDependencies", Copy::class) {
	val buildDirectory = layout.buildDirectory.get()
    from(configurations.runtimeClasspath).into("$buildDirectory/jars")
}

task("copyJar", Copy::class) {
	val buildDirectory = layout.buildDirectory.get()
    from(tasks.jar).into("$buildDirectory/jars")
}

// run: gradle clean jpackage
// installer will be created in build/dist.
tasks.jpackage {
	val buildDirectory = layout.buildDirectory.get()

    dependsOn("build", "copyDependencies", "copyJar")

    input  = "$buildDirectory/jars"
    destination = "$buildDirectory/dist"

    appName = "oripa"
    vendor = "oripa"

    mainJar = tasks.jar.get().archiveFileName.get()
    mainClass = "oripa.ORIPA"

    javaOptions = listOf("-Dfile.encoding=UTF-8")

	// Windows specific parameters will be processed only during Windows build
	winMenu = true
	winDirChooser = true

    windows {
    
    }
}